### ISSUE TITLE
Negative segment duration in `p1.dev.mdtm`

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-db-odessa-ami#1]
https://github.com/pyannote/pyannote-db-odessa-ami/blob/develop/AMI/data/p1.dev.mdtm#L1938

```
ES2011c.Array1-03 1 78.122 -0.12097 speaker NA unknown FEE043
```

**Comment by glynpu** [comment]
Also in p1.trn.mdtm, line 4206

EN2005a.Array1-03 1 91.472 -1.0107 speaker NA unknown FEE085

**Comment by hbredin** [comment]
Thanks for the feedback.

However, I am not sure what to do with those weird segments...

**Comment by MohanKrishna-RC** [comment]
Hi, 
Can you tell us how to get the mdtm format you're using. How to get our datasets in the format used in pyannote.db.gameofthrones
