### ISSUE TITLE
couldn't find audio files from given path in db.yml

### ISSUE THREAD

**Issue by Rehan-Ahmad** [pyannote/pyannote-db-odessa-ami#11]
Hi. 
I followed the steps give here https://github.com/pyannote/pyannote-db-odessa-ami from the beginning, but my code doesn't get train / test files from the path I set in ~/.pyannote/db.yml.

In my case I copied 'AMI: /home/rehan/AMI_data/*/{uri}.wav' in db.yml.  
Here is the error:

`Traceback (most recent call last):                                                                                                                                                                                   File "pyann.py", line 9, in <module>                                                                                                                                                                                 for current_file in protocol.test():                                                                                                                                                                             File "/home/rehan/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/protocol/speaker_diarization.py", line 157, in test                                                                          yield self.preprocess(item)                                                                                                                                                                                      File "/home/rehan/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/protocol/protocol.py", line 89, in preprocess                                                                                current_file[key] = preprocessor(current_file)                                                                                                                                                                   File "/home/rehan/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/util.py", line 316, in __call__                                                                                              raise ValueError(msg.format(uri=uri))                                                                                                                                                                          ValueError: Could not find file "EN2002b.Mix-Headset".`

**Comment by hbredin** [comment]
I just updated the README file as it was not up-to-date (see 372d870)

**Comment by Rehan-Ahmad** [comment]
Many thanks.

**Comment by Rehan-Ahmad** [comment]
There are some more updates required:

1. Please update following lines in download.sh:
    `echo "Now add the following line to your ~/.pyannote/db.yml file"
     echo "AMI: $DLFOLDER/*/audio/{uri}.wav"`

2. Under Test/ Evaluation heading of Speaker diarization protocol, where does `process_file( )` came from ?

**Comment by hbredin** [comment]
1. Feel free to contribute a fix! I'd gladly merge a pull request fixing this issue. 
2. You have to write it :-) This is just meant as an example on how to evaluate a diarization system.
